const types = {
  COMPUTE_EMPTY_COLONY: 'COMPUTE_EMPTY_COLONY',
  CHANGE_FIELD_SIZE: 'CHANGE_FIELD_SIZE',
  CHANGE_CELL_STATE: 'CHANGE_CELL_STATE',
  CREATE_LIST_0F_CELLS_FOR_CHECK: 'CREATE_LIST_0F_CELLS_FOR_CHECK',
  CALCULATE_NEXT_GENERATION: 'CALCULATE_NEXT_GENERATION',
};

export default types;
